// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQpPQ4WREbopoN6SYY9OUBr-u8QppKezg',
    appId: '1:653737069071:web:661dc54d7115c858c4317a',
    messagingSenderId: '653737069071',
    projectId: 'dots-390713',
    authDomain: 'dots-390713.firebaseapp.com',
    storageBucket: 'dots-390713.appspot.com',
    measurementId: 'G-ZV1D4GWYKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBda2fhXzNZMFU4Z0LwZHcUSWtXgMDo444',
    appId: '1:653737069071:android:e6d8409562a3fffdc4317a',
    messagingSenderId: '653737069071',
    projectId: 'dots-390713',
    storageBucket: 'dots-390713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpioLnsmfIR_d6IR0m8C3wVJb9t6s2QMQ',
    appId: '1:653737069071:ios:0ea17a44d83e2d6ac4317a',
    messagingSenderId: '653737069071',
    projectId: 'dots-390713',
    storageBucket: 'dots-390713.appspot.com',
    iosClientId: '653737069071-p0f89slnb1gcef1u4kegktvpnohs3b8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninetynineDots',
  );
}
